POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImvDpHl0dMOkasOkIiwiaWQiOiI2MmZmNGM4MTkzMDk3MzZiNjQzZDAxZDciLCJpYXQiOjE2NjA4OTg0NzV9.lRgKMifKrr0uLokfmGnMqHZk5EzWicBFTGaaE2tUnk8

{
    "title": "bloggi",
    "author": "sanaseppo",
    "url": "asdfasdfasd",
    "likes": 70
}